services:
  backend:
    build: ./backend
    image: final-nodejs-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/products"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    image: final-nodejs-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
        # condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge